include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    unawaited_futures: true
    # avoid_dynamic_calls: true
    use_key_in_widget_constructors: true
    avoid_renaming_method_parameters: true
    avoid_classes_with_only_static_members: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
  errors:
    always_use_package_imports: error
    always_declare_return_types: error
    unawaited_futures: error
    # avoid_dynamic_calls: error
    cancel_subscriptions: error
    invalid_annotation_target: ignore
